<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <OutputPath>Output</OutputPath>
        <PublishDir>$(MSBuildProjectDirectory)\..\Publish\$(Configuration)\</PublishDir>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <WarningsAsErrors>Nullable</WarningsAsErrors>
        <AnalysisLevel>latest</AnalysisLevel>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <TieredPGO>true</TieredPGO>
        <InvariantGlobalization>true</InvariantGlobalization>
        <ServerGarbageCollection>false</ServerGarbageCollection>
        <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
        <RootNamespace>Engikitty</RootNamespace>
        <AssemblyName>Engikitty</AssemblyName>
        <NoWarn>CS1591</NoWarn>
        <DisableTransitiveFrameworkReferences>true</DisableTransitiveFrameworkReferences>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NetCord" Version="1.0.0-beta.18" />
        <PackageReference Include="NetCord.Services" Version="1.0.0-beta.18" />
        <PackageReference Include="Microsoft.Data.Sqlite" Version="*" />
        <PackageReference Include="GroqApiLibrary" Version="*" />
        <PackageReference Include="Edge_tts_sharp" Version="1.1.7" />
        <PackageReference Include="NAudio.WinForms" Version="2.0.0" ExcludeAssets="all" />
    </ItemGroup>
    
    <ItemGroup>
        <Reference Include="LingvaSharp.dll" HintPath="./Deps/LingvaSharp.dll" />
    </ItemGroup>

</Project>